version: '3'
services:
  app:
    build: .
    container_name: printer-app
    ports: 
      - '8880:8880'
    restart: on-failure
    depends_on:
      - database
    environment:
      - PATH_TO_FILES="/files"

  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=printer
      - DATABASE_HOST=database