version: '3'
services:
  app:
    build: .
    container_name: printer-app
    ports: 
      - '8880:8880'
    restart: on-failure
    depends_on:
      - database
    environment:
      - APP_DB_USER=postgres
      - APP_DB_HOST=database
      - APP_DB_PASSWORD=password
      - APP_DB_DBNAME=printer
      - APP_DB_PORT=5432
      - APP_PATH_TO_FILES=/files
      - APP_PORT=8880
      - APP_ADMIN_LOGIN=admin
      - APP_ADMIN_EMAIL=admin@admin.admin
      - APP_ADMIN_PASSWORD=adminpassword

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=printer
      - DATABASE_HOST=database